// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhSt-3YbEi2_cOHgLkEAIsfsqQ3jTch6I',
    appId: '1:938204263493:web:645151767bd3166abe1f2c',
    messagingSenderId: '938204263493',
    projectId: 'socialframe-bd633',
    authDomain: 'socialframe-bd633.firebaseapp.com',
    storageBucket: 'socialframe-bd633.appspot.com',
    measurementId: 'G-PP8WL2893F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNFOHhZt-GlzJOKe0LEekRCrVbmLY1_-o',
    appId: '1:938204263493:android:13659764ae6a3840be1f2c',
    messagingSenderId: '938204263493',
    projectId: 'socialframe-bd633',
    storageBucket: 'socialframe-bd633.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoDL22g-7goLdIYA2ZsEs9ZupJn8Qx57A',
    appId: '1:938204263493:ios:54d561aef07445a8be1f2c',
    messagingSenderId: '938204263493',
    projectId: 'socialframe-bd633',
    storageBucket: 'socialframe-bd633.appspot.com',
    iosClientId: '938204263493-ealalc34blb8cfeq47vnt42au6fq0mjl.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialframe',
  );
}
